import = []

live_config_reload = true

[shell]
program = "/usr/bin/zsh"
args = ["-l"]

[window]
startup_mode = "Windowed"
title = ""
dynamic_title = true 
decorations_theme_variant = "None"
decorations = "Full"
opacity = 0.8
blur = true 

[scrolling]
history = 10000
multiplier = 3


[font.bold]
family ="JetBrainsMono Nerd Font"
style = "Bold"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family ="JetBrainsMono Nerd Font"

[font.normal]
family ="JetBrainsMono Nerd Font"
style = "regular"

[colors]
#foreground = "#d8d8d8"
#background = "#181818"
#dim_foreground = "#828482"
#bright_foreground = "None"
#cursor = { text = "CellBackground", cursor = "CellForeground" }

# foreground = "<string>"
# Default: "#d8d8d8"

# background = "<string>"
# Default: "#181818"

# dim_foreground = "<string>"
# If this is not set, the color is automatically calculated based on the foreground color.
# Default: "#828482"

# bright_foreground = "<string>"
# This color is only used when draw_bold_text_with_bright_colors is true.
# If this is not set, the normal foreground will be used.
# Default: "None"

[colors.search]
matches = { foreground = "#181818", background = "#ac4242" }
focused_match = { foreground = "#181818", background = "#f4bf75" }

[colors.hints]
start = { foreground = "#181818", background = "#f4bf75" }
end = { foreground = "#181818", background = "#ac4242" }

[colors.normal]
black = "#181818"
red = "#ac4242"
green = "#90a959"
yellow = "#f4bf75"
blue = "#6a9fb5"
magenta = "#aa759f"
cyan = "#75b5aa"
white = "#d8d8d8"

[colors.bright]
black = "#6b6b6b"
red = "#c55555"
green = "#aac474"
yellow = "#feca88"
blue = "#82b8c8"
magenta = "#c28cb8"
cyan = "#93d3c3"
white = "#f8f8f8"


[colors.dim]
black = "#0f0f0f"
red = "#712b2b"
green = "#5f6f3a"
yellow = "#a17e4d"
blue = "#456877"
magenta = "#704d68"
cyan = "#4d7770"
white = "#8e8e8e"

[bell]
animation = "Linear"
duration = 0
#color = "#ffffff"
#command = "None"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"
save_to_clipboard = false

[cursor]
style = { shape = "Block", blinking = "Off" }
unfocused_hollow = true
thickness = 0.15

[mouse]
hide_when_typing = false

# [[keyboard.bindings]]
# key = "V"
# mods = "Control"
# action = "Paste"
#
# [[keyboard.bindings]]
# key = "C"
# mods = "Control"
# action = "Copy"
